# 暴露监控信息
# management 是所有actuator的配置
# management.endpoint.端点名.xxx：对某个端点的具体配置
management:
  endpoint:
    health:
      show-details: always # 配置单个端点 always：总是显示详细信息

    info:
      enabled: true # 开启某一个端点

    beans:
      enabled: true # 开启某一个端点

    metrics:
      enabled: true # 开启某一个端点

  endpoints:
    enabled-by-default: true # 默认开启所有监控端点
    web:
      exposure:
        include: '*' # 以web方式暴露所有端点


spring:
  redis:
    host: @example.com  # redis服务器地址(公网地址)  第一种方式 分开来配置
    port: 6379  # 端口号
    password: Lfy123456 # 密码
    client-type: jedis  # 明确申明连接工程就是jedis
      jedis:
        pool:
          max-active: 10 # 最大线程数


  #格式 redis://用户: 密码 rids服务器地址(公网地址) :端口号
    #url: redis://lfy:Lfy123456@example.com:6379  第二种方式

#    client-type: lettuce # 如果是lettuce
#      lettuce:
#      pool:
#        max-active: 10  # 最大线程数
#        min-idle: 5  # 最小空闲的



  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

# 配置mybatis规则
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml # 指定mybatis全局配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml  # 指定sql映射文件mapper.xml
  configuration:  # 指定mybatis全局配置文件中的相关配置
    map-underscore-to-camel-case: true #  开启驼峰命名
#    type: com.zaxxer.hikari.util.DriverDataSource